const DEFAULT_COOKIES_DAY = 30 * 24 * 60 * 60 * 1000; // 30 days
const USER_ID = ["userId"];
const CATEGORY_ID = ["categoryId"];
const PRODUCT_ID = ["productId"];
const REVIEW_ID = ["reviewId"];
const QUESTION_ID = ["productQuestionId"];
const USER_ID_AND_REVIEW_ID = [...USER_ID, ...REVIEW_ID];
const USER_ID_AND_PRODUCT_ID = [...USER_ID, ...PRODUCT_ID];
const PRODUCT_ID_AND_REVIEW_ID = [...PRODUCT_ID, ...REVIEW_ID];
const PRODUCT_ID_AND_QUESTION_ID = [...PRODUCT_ID, ...QUESTION_ID];

const REPORTED_ID = ["reportId"];

const ADDRESS_DIRECTION_ID = ["addressDirectionId"];
const USER_ID_AND_ADDRESS_DIRECTION_ID = [...USER_ID, ...ADDRESS_DIRECTION_ID];

export {
  REPORTED_ID,
  DEFAULT_COOKIES_DAY,
  USER_ID,
  PRODUCT_ID,
  CATEGORY_ID,
  REVIEW_ID,
  USER_ID_AND_REVIEW_ID,
  USER_ID_AND_PRODUCT_ID,
  PRODUCT_ID_AND_REVIEW_ID,
  PRODUCT_ID_AND_QUESTION_ID,
  ADDRESS_DIRECTION_ID,
  USER_ID_AND_ADDRESS_DIRECTION_ID,
};
