paths:
  /auth/signup:
    post:
      tags:
        - Auth
      summary: "User Signup"
      description: "Create a new user account with a username, email, and password."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignupInput"
      responses:
        "201":
          description: "User account successfully created."
          content:
            application/json:
              schema:
                type: object
                properties:
                  userSaved:
                    type: object
                    description: "Details of the newly created user."
                    properties:
                      _id:
                        type: string
                        description: "The unique identifier of the user."
                        example: "60d5f7f2b5c7d41c5c8c8e1b"
                      username:
                        type: string
                        description: "The username of the user."
                        example: "john_doe"
                      email:
                        type: string
                        description: "The email address of the user."
                        example: "john@example.com"
                  accessToken:
                    type: string
                    description: "JWT access token for the user."
                    example: "eyJhbGciOiJIUzI1NiIsInR..."
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: "#/components/schemas/BadRequestError"
                  - $ref: "#/components/schemas/UserAlreadyExistsError"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

  /auth/login:
    post:
      tags:
        - Auth
      summary: "User login"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginInput"

      responses:
        "200":
          description: "User logged in successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    example: "605c72f7b1c7e925a0e8e8c4"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        "404":
          description: "Not Found - User not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

  /auth/logout:
    post:
      tags:
        - Auth
      summary: "User Logout"
      description: "Log out the user by clearing the access and refresh tokens."
      security:
        - cookieAuth: [] # Requires accessToken for authentication
        - refreshTokenAuth: [] # Requires refreshToken for session management
      responses:
        "200":
          description: "Successful logout"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "Logged out"
        "401":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

  /auth/token/validate:
    get:
      tags:
        - Auth
      summary: "Validate Access Token"
      description: "Validate the access token using the refresh token stored in cookies."
      parameters:
        - in: query
          name: token
          description: Token
          required: true
          schema:
            type: string
            example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
      responses:
        "200":
          description: "Access token successfully validated"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
        "403":
          description: "Invalid refresh token"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidRefreshTokenError"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

  /auth/token/refresh:
    get:
      tags:
        - Auth
      summary: "Refresh Access Token"
      description: "Refresh the access token using the refresh token stored in cookies."
      security:
        - cookieAuth: [] # Requires refreshToken for authentication
      responses:
        "200":
          description: "Access token successfully refreshed"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
        "403":
          description: "Invalid refresh token"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidRefreshTokenError"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

  /auth/user/me:
    get:
      tags:
        - Auth
      summary: "Get Authenticated User Info"
      description: "Retrieve the information of the currently authenticated user."
      security:
        - cookieAuth: [] # Requires authentication via cookies
      responses:
        "200":
          description: "Successfully retrieved authenticated user information."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"

  /auth/confirmation-email:
    post:
      tags:
        - Auth
      summary: Confirmation email
      description: Confirmation email
      parameters:
        - in: query
          name: token
          description: Token
          required: true
          schema:
            type: string
            example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"

      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "User confirmed successfully"
                    description: "The message of the response."
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
        "404":
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  auth/send-confirmation-email:
    post:
      tags:
        - Auth
      summary: send Confirm email
      description: send Confirm email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendConfirmationEmailRequest"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "A confirmation email has been sent."
                    description: "The message of the response."
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
        "404":
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

  auth/send-forgot-password-email:
    post:
      tags:
        - Auth
      summary: "Send forgot password email"
      description: "Send forgot password email"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendConfirmationEmailRequest"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "A reset password has been sent."
                    description: "The message of the response."
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

  /auth/change-password:
    post:
      tags:
        - Auth
      summary: "Change Password"
      description: "Change the password of the authenticated user."
      security:
        - cookieAuth: [] # Requires authentication via cookies
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangePasswordInput"
      responses:
        "200":
          description: "Password changed successfully."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Password updated successfully"
        "401":
          description: "Unauthorized access due to missing or invalid token."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
        "404":
          description: "User not found."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

  /auth/forgot-password:
    post:
      tags:
        - Auth
      summary: "Send forgot password email"
      description: "Send forgot password email"
      parameters:
        - in: query
          name: token
          description: Token
          required: true
          schema:
            type: string
            example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ForgotPasswordRequest"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: "Password updated successfully."
                    description: "The message of the response."

        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
