paths:
  /products/{productId}/reviews:
    get:
      tags:
        - Review
      summary: "Retrieve a paginated list of reviews for a specific product"
      description: "Fetches paginated reviews for a given product, including author details. Supports pagination parameters."
      parameters:
        - name: productId
          in: path
          required: true
          description: "The ID of the product to retrieve reviews for."
          schema:
            type: string

        - name: page
          in: query
          required: false
          description: "The page number to retrieve."
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          required: false
          description: "The number of categories to return per page."
          schema:
            type: integer
            minimum: 1
            default: 10
        - name: sort
          in: query
          required: false
          description: "The field by which to sort categories."
          schema:
            type: string
            enum:
              - createdAt
              - -createdAt
              - updatedAt
              - -updatedAt
            default: "-createdAt"
      responses:
        "200":
          description: "A paginated list of reviews for the specified product."
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/PaginationResult"
                  - type: object
                properties:
                  docs:
                    type: array
                    items:
                      $ref: "#/components/schemas/Review"
        "404":
          description: "Product not found or no reviews available for this product."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"
        "500":
          description: "Internal server error."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

    post:
      tags:
        - Review
      summary: "Create a review for a product"
      description: "Adds a new review to the specified product, with the authenticated user as the author."
      security:
        - cookieAuth: []
      parameters:
        - name: productId
          in: path
          required: true
          description: "The ID of the product to add a review to."
          schema:
            type: string

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReviewInput" # Reference to the review input schema
      responses:
        "201":
          description: "Review created successfully."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Review" # Reference to the created review schema
        "400":
          description: "Bad request due to invalid input."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        "401":
          description: "Unauthorized access due to missing or invalid token."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
        "404":
          description: "Product not found."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"
        "500":
          description: "Internal server error."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  /products/{productId}/reviews/{reviewId}:
    get:
      tags:
        - Review
      summary: "Retrieve a specific review by its ID"
      description: "Fetches a single review for a specified product, including author and product details."
      parameters:
        - name: productId
          in: path
          required: true
          description: "The ID of the product associated with the review."
          schema:
            type: string

        - name: reviewId
          in: path
          required: true
          description: "The ID of the review to retrieve."
          schema:
            type: string

      responses:
        "200":
          description: "Review details for the specified review ID."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Review" # Reference to the review schema with populated fields
        "404":
          description: "Review not found for the specified product or review ID."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"
        "500":
          description: "Internal server error."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

    put:
      tags:
        - Review
      summary: "Update a specific review on a product"
      description: "Updates the specified review for the product, ensuring the authenticated user is the review author or has admin privileges."
      security:
        - cookieAuth: []
      parameters:
        - name: productId
          in: path
          required: true
          description: "The ID of the product associated with the review."
          schema:
            type: string

        - name: reviewId
          in: path
          required: true
          description: "The ID of the review to update."
          schema:
            type: string

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReviewInput" # Reference to the review input schema
      responses:
        "200":
          description: "Review updated successfully."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Review" # Reference to the updated review schema
        "400":
          description: "Bad request due to invalid input."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestError"
        "401":
          description: "Unauthorized access due to missing or invalid token."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
        "403":
          description: "Forbidden due to lack of permissions."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForbiddenError"
        "404":
          description: "Product or review not found."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"
        "500":
          description: "Internal server error."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

    delete:
      tags:
        - Review
      summary: "Delete a specific review on a product"
      description: "Deletes the specified review from the product, ensuring the authenticated user is the review author or has admin privileges."
      security:
        - cookieAuth: []
      parameters:
        - name: productId
          in: path
          required: true
          description: "The ID of the product associated with the review."
          schema:
            type: string

        - name: reviewId
          in: path
          required: true
          description: "The ID of the review to delete."
          schema:
            type: string

      responses:
        "204":
          description: "Review deleted successfully."
        "403":
          description: "Forbidden due to lack of permissions."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForbiddenError"
        "401":
          description: "Unauthorized access due to missing or invalid token."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnauthorizedError"
        "404":
          description: "Product or review not found."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundError"
        "500":
          description: "Internal server error."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
